CREATE DATABASE IF NOT EXISTS slot_sense CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE slot_sense;

CREATE TABLE usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(120) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  senha_hash VARCHAR(255) NOT NULL,
  is_admin TINYINT(1) DEFAULT 1,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE jogos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(150) NOT NULL,
  imagem VARCHAR(255) DEFAULT NULL,
  link_affiliate VARCHAR(500) DEFAULT NULL,
  porcentagem INT DEFAULT 50,
  popularidade INT DEFAULT 0,
  atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE cliques (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  jogo_id INT NOT NULL,
  ip VARCHAR(45),
  user_agent TEXT,
  referrer VARCHAR(500),
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (jogo_id) REFERENCES jogos(id) ON DELETE CASCADE
);
